name: inbox_clients
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+5
#flutterten clean && flutterten pub get && flutterten build apk --target-platform=android-arm --release
environment:
  sdk: ">=2.12.0 <3.0.0"
  #flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+4
  connectivity: ^3.0.6
  image: ^3.0.2
  get: 4.6.1
  cached_network_image: ^3.0.0
  flutter_screenutil: ^5.4.0
  flutter_svg: ^1.0.3 #0.22.0
  logger: ^1.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  intl: ^0.17.0
  url_launcher: ^6.0.17
  shared_preferences: ^2.0.11
  dio: ^4.0.4
  #introduction_screen: ^2.1.0
  infinite_scroll_pagination: ^3.1.0
  device_info: 2.0.2
  pin_code_fields: ^7.3.0
  firebase_core: ^1.10.0
  firebase_messaging: ^11.2.11
  flutter_local_notifications: ^9.1.5 #9.0.3 #9.5.3+1 #9.1.5
  local_auth: ^1.1.8
  grouped_list: ^4.1.0
  google_maps_flutter: ^2.1.3 #2.1.6 #2.1.3
  google_place: ^0.4.3
  #  geolocator: 9.0.0
  #  geolocator: ^8.0.0
  geolocator: ^9.0.2
  #  geocoding: ^2.0.1
  geocoding: ^2.0.5
  video_player: ^2.2.7
  chewie: ^1.2.2
  #  qr_code_scanner: ^0.6.1
  qr_code_scanner: ^1.0.1
  share: ^2.0.4
  #firebase_crashlytics: ^2.4.5
  sqflite: ^2.0.2
  path_provider: ^2.0.8
  webview_flutter: ^3.0.0
  #  permission_handler: ^8.3.0
  permission_handler: ^10.2.0
  expandable: ^5.0.1
  signature: ^5.0.0
  #  alt_sms_autofill: ^1.0.0
  location: ^4.3.0
  flutter_polyline_points: ^1.0.0
  cloud_firestore: ^3.1.10
  #uni_links: ^0.5.1
  flutter_rating_bar: ^4.0.0
  # flutter_webview_plugin: ^0.4.0
  #  pay: ^1.0.6
  pay: ^1.0.10
  #  moyasar_payment: ^0.1.2
  showcaseview: ^1.1.7
  flutter_widget_from_html: ^0.8.5
  firebase_crashlytics: ^2.8.1
  badges: ^2.0.3
  #smart_auth: ^1.0.6
  android_sms_retriever: ^1.3.3
  #  mad_pay: ^2.2.11
  #  fake_cloud_firestore: ^1.2.2
  #  dart_jsonwebtoken: ^2.4.1
  #  square_in_app_payments: ^1.7.3
  square_in_app_payments: ^1.7.5
#  sms_retriever: ^1.0.0
dependency_overrides:
  firebase_core_platform_interface: 4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  #  plugin:
  #    platforms:
  #      android:
  #        package: io.flutter.plugins.googlemaps
  #        pluginClass: GoogleMapsPlugin
  #      ios:
  #        pluginClass: FLTGoogleMapsPlugin
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svgs/
    - assets/png/
    - assets/fonts/
    - assets/gif/
    - assets/video/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/oriya_mn_regular.ttc
          weight: 400
    - family: simi_bold
      fonts:
        - asset: assets/fonts/oriya_mn_regular.ttc
          weight: 600

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
